export { HomePage } from './HomePage'
export { DashboardPage } from './DashboardPage'
export { ScorecardPage } from './ScorecardPage'
export { LoginPage } from './LoginPage'
export { SignupPage } from './SignupPage'
export { VerifyEmailPage } from './VerifyEmailPage'
export { ForgotPasswordPage } from './ForgotPasswordPage'
export { ResetPasswordPage } from './ResetPasswordPage'
export { AdminPage } from './AdminPage'
export { NotFoundPage } from './NotFoundPage'

